#!/usr/bin/env python3

# Can encrypt and decrypt

def encrypt () :
  print ( 'hello encrypt!' );

def decrypt () :
  print ( 'hello decrpyt!' );


def main () :
  print ( 'Hello world!' );

  
if __name__ == '__main__' :
  main();
  